# Generated by Django 5.2.10 on 2026-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='department',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
