# Generated by Django 5.2.10 on 2026-02-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_grievance'),
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grievance',
        ),
    ]
