# Generated by Django 5.2.10 on 2026-02-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='grievance',
        ),
    ]
