# Generated by Django 5.2.10 on 2026-02-10 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_grievance'),
        ('grievances', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='grievance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='grievances.grievance'),
        ),
    ]
